[package]
name = "integration-tests"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "cfsctl-integration-tests"
path = "src/main.rs"

[dependencies]
anyhow = "1"
xshell = "0.2"
libtest-mimic = "0.8"
linkme = "0.3"
paste = "1"
rustix = { version = "1.0.0", default-features = false, features = ["process"] }
tempfile = "3"

[lints]
workspace = true
