[package]
name = "integration-tests"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "cfsctl-integration-tests"
path = "src/main.rs"

[dependencies]
anyhow = "1"
cap-std-ext = "4.0"
composefs = { path = "../composefs" }
libtest-mimic = "0.8"
linkme = "0.3"
ocidir = "0.6"
paste = "1"
rustix = { version = "1.0.0", default-features = false, features = ["process"] }
serde_json = "1.0"
tar = "0.4"
tempfile = "3"
xshell = "0.2"

[lints]
workspace = true
